Update patch set 1
Patch Set 1:

this breaks compile for klte....

In file included from hardware/qcom/audio-caf/post_proc/bundle.c:29:0:
hardware/qcom/audio-caf/post_proc/bundle.h:24:33: fatal error: sound/audio_effects.h: No such file or directory
compilation terminated.

Patch-set: 1
Reviewer: Matt Filetto <2814@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0